# Site
name: "DinoHub"
title: "DinoHub"
description: "TechBlog for Dinos"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-172682310-1'
disqus: 'dinohub-github-io'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  jax:
    name: Jax
    display_name: Kah Siong, a.k.a Jax
    gravatar: 4650582bde3dbf1b7e74cba2cf11284f
    email: jax79sg@yahoo.com.sg
    web: 
    twitter: ''
    description: "Chup Cai Png Engineer"
  jadle:
    name: Jadle
    display_name: Jadle
    description: "Just Another Deep Learning Enthusiast"  
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  levan:
    name: Evan
    display_name: levan
    gravatar: aff1df4dc883f795599bf68e71f137f1
    email: lingevan0208@gmail.com.sg
    web: https://github.com/levan92
    twitter: https://twitter.com/0E_92
    description: "Bbt Adventurer"
  cvappstore:
    name: cvappstore
    display_name: cvappstore
    gravatar: ''
    email: ''
    web: ''
    twitter: ''
    description: ''
  jinming:
    name: Jin
    display_name: Jin Ming
    gravatar: ''
    email: jinmingteo95@gmail.com
    web: https://github.com/jinmingteo
    twitter: ''
    description: "Learning Machine"
  kayne_ivan_west:
    name: kayne_ivan_west
    display_name: kayne_ivan_west
    gravatar: ''
    email: ''
    web: ''
    twitter: ''
    description: ''
  cshikai:
    name: Kai
    display_name: cshikai
    gravatar: b790bb64fd6c4ad8b4e9ab598f4d7cc3
    email: chongshikai@gmail.com
    web:  https://github.com/cshikai
    twitter: ''
    description: "Data Scientist"
  dhinterns:
    name: DigitalHubInterns
    display_name: DigitalHubInterns
    gravatar: 0bc4040d45ecb259c4fa29eef763dd57
    email: ''
    web:  ''
    twitter: ''
    description: "Collective archive of all the innovative work done by our interns at Digital Hub"
  ernestlwt:
    name: ernestlwt
    display_name: ernestlwt
    gravatar: '21fdd617b75fc3ef81038c9dae82bd28'
    email: 'ernestlimwoonteng@gmail.com'
    web:  'https://github.com/ernestlwt'
    twitter: ''
    description: "Level 3 Beginner"
  dave:
    name: dave
    display_name: dave
    gravatar: ''
    email: 'wongdavid610@gmail.com'
    web:  'https://github.com/dbxwong'
    twitter: ''
    description: 'will work for coffee'
  

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
